services:
  my-mongodb:
    image: mongo:latest
    container_name: my-mongodb
    ports:
      - 27019:27017
    volumes:
      - ./mongo/seed.js:/docker-entrypoint-initdb.d/seed.js
  watchmen-backend :
    image: watchmen-backend
    container_name: watchmen-backend
    ports:
      - 8888:80
    environment :
      PROJECT_NAME: matryoshka
      STORAGE_ENGINE: mongo
      MONGO_HOST : my-mongodb
#      MONGO_USERNAME : watchmen
#      MONGO_PASSWORD : watchmen-pwd
      MONGO_PORT : 27017
      MONGO_DATABASE : watchmen
      PRESTO_HTTP_URL : http://localhost:8080
      PRESTO_ON : 'False'
      HOST_URL : http://localhost:8080
    volumes:
      - "./watchmen-doll/temp/rotating.log:/app/temp/rotating.log"





