name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: cd docker && docker-compose up -d
      - name: Test
        run: docker run   --mount type=bind,source="$(pwd)"/test_folder,target=/app/test_folder --mount type=bind,source="$(pwd)"/pdf,target=/app/pdf  --network host  -e SITE=local-docker -e INIT=True  ghcr.io/indexical-metrics-measure-advisory/watchmen-doll-test-doll:latest
